# Titanic 4 worked - modified to remove all Null rows

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import preprocessing
df = pd.read_table('train.csv',
                   sep=',',
                  header=0)
# Output printing out first 5 columns
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [2]:
# Lable male as 0, female as 1
df['Sex'] = df.Sex.map({'male':0, 'female':1})
print(df.shape)
df.head() # returns (rows, columns)

(891, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [3]:
df_f = df.loc[:, ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Survived']]
print(df_f.shape)
df_f.head()

(891, 7)


Pclass  Sex   Age  SibSp  Parch     Fare  Survived
0       3    0  22.0      1      0   7.2500         0
1       1    1  38.0      1      0  71.2833         1
2       3    1  26.0      0      0   7.9250         1
3       1    1  35.0      1      0  53.1000         1
4       3    0  35.0      0      0   8.0500         0

In [4]:
df_cleaned = df_f.dropna()
print(df_cleaned.shape)
df_cleaned.head()

(714, 7)


Pclass  Sex   Age  SibSp  Parch     Fare  Survived
0       3    0  22.0      1      0   7.2500         0
1       1    1  38.0      1      0  71.2833         1
2       3    1  26.0      0      0   7.9250         1
3       1    1  35.0      1      0  53.1000         1
4       3    0  35.0      0      0   8.0500         0

In [5]:
X = df_cleaned.values[:,0:-1]
X.shape

(714, 6)

In [6]:
Y = df_cleaned.values[:,-1]
Y.shape

(714,)

In [7]:
X_scaled = preprocessing.scale(X)
X_scaled

array([[ 0.91123237, -0.75905134, -0.53037664,  0.52457013, -0.50589515,
        -0.51897787],
       [-1.47636364,  1.31743394,  0.57183099,  0.52457013, -0.50589515,
         0.69189675],
       [ 0.91123237,  1.31743394, -0.25482473, -0.55170307, -0.50589515,
        -0.50621356],
       ..., 
       [-1.47636364,  1.31743394, -0.73704057, -0.55170307, -0.50589515,
        -0.08877362],
       [-1.47636364, -0.75905134, -0.25482473, -0.55170307, -0.50589515,
        -0.08877362],
       [ 0.91123237, -0.75905134,  0.15850313, -0.55170307, -0.50589515,
        -0.50952283]])

In [8]:
logreg = LogisticRegression()
logreg.fit(X_scaled, Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [9]:
print(logreg.intercept_, logreg.coef_)

[-0.50203079] [[-1.01348639  1.25016542 -0.61891121 -0.33913476 -0.05238883  0.12186989]]


In [10]:
df_t = pd.read_table('test.csv',
                   sep=',',
                  header=0)
# Output printing out first 5 columns
df_t.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [11]:
df_testf = df_t.loc[:, ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']]
df_testf['Sex'] = df_testf.Sex.map({'male':0, 'female':1})
print(df_testf.shape)
df_testf.head()

(418, 6)


Pclass  Sex   Age  SibSp  Parch     Fare
0       3    0  34.5      0      0   7.8292
1       3    1  47.0      1      0   7.0000
2       2    0  62.0      0      0   9.6875
3       3    0  27.0      0      0   8.6625
4       3    1  22.0      1      1  12.2875

In [12]:
df_testf.dropna()
print(df_testf.shape)

(418, 6)


In [13]:
#X_t_scaled = preprocessing.scale(X_T)

X_T = df_testf.values[:,:]
X_T = np.nan_to_num(X_T)
X_T.shape


X_t_scaled = preprocessing.scale(X_T)
X_t_scaled

array([[ 0.87348191, -0.75592895,  0.59480137, -0.49947002, -0.4002477 ,
        -0.49663711],
       [ 0.87348191,  1.32287566,  1.30589556,  0.61699237, -0.4002477 ,
        -0.5114971 ],
       [-0.31581919, -0.75592895,  2.15920859, -0.49947002, -0.4002477 ,
        -0.46333473],
       ..., 
       [ 0.87348191, -0.75592895,  0.82235151, -0.49947002, -0.4002477 ,
        -0.50701688],
       [ 0.87348191, -0.75592895, -1.3678186 , -0.49947002, -0.4002477 ,
        -0.49268018],
       [ 0.87348191, -0.75592895, -1.3678186 ,  0.61699237,  0.61989583,
        -0.23626278]])

In [14]:
#logreg.predict(X_t_scaled)
df_y = pd.read_table('gender_submission.csv',
                   sep=',',
                  header=0)
# Output printing out first 5 columns
print('shape: before dropping na')
print(df_y.shape)
print('shape: after dropping na')
df_y.dropna()
print(df_y.shape)
df_y.head()

shape: before dropping na
(418, 2)
shape: after dropping na
(418, 2)


PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [15]:
print('Since before/after dropna, the shape is the same. So, we now know there is no NA value in test data')

print('\n\n Now check shape if test label')
y_test = df_y.loc[:, ['Survived']]
y_test = y_test.squeeze()
y_test.shape

Since before/after dropna, the shape is the same. So, we now know there is no NA value in test data


 Now check shape if test label


(418,)

In [16]:
 logreg.predict(X_t_scaled)

array([ 0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,
        0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,
        0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,
        0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,
        1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        1.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,
        1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0

In [17]:
accuracy_score = logreg.score(X_t_scaled, y_test)
print(accuracy_score)

0.916267942584
